spring:
  datasource:
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    name: blog

  sql:
    init:
      mode: always

  spring_profiles_active=prod
  PROD_DB_HOST=containers-us-west-103.railway.app
  PROD_DB_PORT=5604
  PROD_DB_NAME=railway
  PROD_DB_PASSWORD=3S8jXLme85lrEhZI9TdF
  PROD_DB_USERNAME=postgres